name: CI
on:
  pull_request:
    branches: [main, develop]

jobs:
  CI:
    runs-on: ${{  matrix.os  }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.13, 1.14, 1.15]

    steps:
      - uses: actions/checkout@v2
      - name: Setup go  ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build package
        run: make build
      - name: Lint code
        run: make lint
      - name: Run tests
        run: make test
      - name: Run e2e tests
        run: |
          python3 -m pip install requests
          ./bin/GotwockAppServer &
          python3 end2end_tests/run_e2e_tests.py
